import foodTable from '../src/food/food.entity';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';

const pool = new Pool({
    connectionString: process.env.DATABASE_URL ?? 'postgres://postgres:123456@localhost:5432/nutridigitaldb',
});

const db = drizzle(pool);

async function seedFoods() {

    //await db.execute(
    //    `ALTER SEQUENCE food_id_seq RESTART WITH 1;`
    //);

    await db.insert(foodTable).values([
        {
            name: "Manzana (200 g)",
            brand: "Frutas del Valle",
            href: "https://media.istockphoto.com/id/1849310621/es/foto/osch%C3%B6nheit-perfektion-ne-apple-a-day.webp?b=1&s=612x612&w=0&k=20&c=n0436pZ0BKQDeh6xkzyOSIpBprq6SvSM17Mk-MeIRss=",
            calories: 122,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 0,
            potassium: 208,
            total_carbs: 30,
            dietary_fiber: 4,
            sugars: 24,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Fruta",
        },
        {
            name: "Banana (150 g)",
            brand: "Frutas del Valle",
            href: "https://media.istockphoto.com/id/2175529470/es/foto/racimo-de-pl%C3%A1tano-por-palabra.webp?b=1&s=612x612&w=0&k=20&c=IE_uUJVr7dbpIA4lw-epXNrhNXwfJix1cMNOoEUJdiA=",
            calories: 134,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 2,
            potassium: 537,
            total_carbs: 34,
            dietary_fiber: 4,
            sugars: 18,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Fruta",
        },
        {
            name: "Cafe (200 ml)",
            brand: "Nescafe",
            href: "https://cdn.pixabay.com/photo/2015/05/07/13/46/cappuccino-756490_640.jpg",
            calories: 74,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 1,
            sodium: 76,
            potassium: 0,
            total_carbs: 13,
            dietary_fiber: 1,
            sugars: 10,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Bebida",
        },
        {
            name: "Medialuna (50 g)",
            brand: "Panaderia",
            href: "https://www.nunziopanificadora.com/wp-content/uploads/2020/05/medialuna-dulce.jpg",
            calories: 158,
            total_fat: 7,
            saturated: 2,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 2,
            cholesterol: 0,
            sodium: 47,
            potassium: 0,
            total_carbs: 20,
            dietary_fiber: 1,
            sugars: 5,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Cerveza (1000 ml)",
            brand: "Quilmes",
            href: "https://static.wixstatic.com/media/d2b1c5_252fb740d86f4fee93b9d1e907648a7f~mv2_d_1728_1928_s_2.png/v1/fill/w_480,h_536,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/d2b1c5_252fb740d86f4fee93b9d1e907648a7f~mv2_d_1728_1928_s_2.png",
            calories: 197,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 17,
            potassium: 85,
            total_carbs: 7,
            dietary_fiber: 0,
            sugars: 1,
            protein: 1,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Bebida",
        },
        {
            name: "Chocolate (40 g)",
            brand: "Arcor",
            href: "https://molti.com.ar/wp-content/uploads/2020/08/CHO-BCO-8-GR.jpg",
            calories: 200,
            total_fat: 11,
            saturated: 7,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 5,
            sodium: 5,
            potassium: 0,
            total_carbs: 25,
            dietary_fiber: 2,
            sugars: 20,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Coca Cola (500 ml)",
            brand: "Coca Cola",
            href: "https://jumboargentina.vtexassets.com/arquivos/ids/782824-800-600?v=638206689771200000&width=800&height=600&aspect=true",
            calories: 140,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 5,
            sodium: 45,
            potassium: 0,
            total_carbs: 39,
            dietary_fiber: 0,
            sugars: 39,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Bebida",
        },
        {
            name: "Hamburguesa (250 g)",
            brand: "Paty",
            href: "https://img.hogar.mapfre.es/wp-content/uploads/2018/09/hamburguesa-sencilla.jpg",
            calories: 516,
            total_fat: 25,
            saturated: 8,
            polyunsaturated: 5,
            monounsaturated: 9,
            trans: 1,
            cholesterol: 92,
            sodium: 712,
            potassium: 835,
            total_carbs: 38,
            dietary_fiber: 5,
            sugars: 10,
            protein: 35,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Yogur descremado (200 g)",
            brand: "Milkaut",
            href: "https://d1on8qs0xdu5jz.cloudfront.net/webapp/images/productos/b/0000007000/7359.jpg",
            calories: 120,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 10,
            sodium: 85,
            potassium: 240,
            total_carbs: 16,
            dietary_fiber: 0,
            sugars: 14,
            protein: 10,
            vitamin_a: 2,
            vitamin_c: 1,
            calcium: 15,
            iron: 0,
            restricciones: "Vegetariano",
            tipo: "Lácteo",
        },
        {
            name: "Pollo a la plancha (150 g)",
            brand: "Granja Campo",
            href: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2irY3g-ROvN-AwI-Fr-6FoKd5VGet8QN7cw&s",
            calories: 275,
            total_fat: 8,
            saturated: 2,
            polyunsaturated: 2,
            monounsaturated: 3,
            trans: 0,
            cholesterol: 90,
            sodium: 70,
            potassium: 300,
            total_carbs: 0,
            dietary_fiber: 0,
            sugars: 0,
            protein: 40,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 6,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Pan integral (2 rebanadas)",
            brand: "Fargo",
            href: "https://www.infobae.com/resizer/v2/PK77XOCX4ZAVFI5AUF3DZRBJNY.jpg?auth=76e68dbb00155c439af1eac05a63dda69fdeef55b11e7a7a33353066e2844d20&smart=true&width=350&height=197&quality=85",
            calories: 140,
            total_fat: 2,
            saturated: 0,
            polyunsaturated: 1,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 200,
            potassium: 80,
            total_carbs: 25,
            dietary_fiber: 4,
            sugars: 3,
            protein: 5,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 4,
            iron: 6,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Huevo duro (1 unidad)",
            brand: "Granja Los Pinos",
            href: "https://images.cookforyourlife.org/wp-content/uploads/2020/06/Hard-Boiled-Eggs-shutterstock_451345444.jpg",
            calories: 78,
            total_fat: 5,
            saturated: 2,
            polyunsaturated: 1,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 186,
            sodium: 62,
            potassium: 63,
            total_carbs: 1,
            dietary_fiber: 0,
            sugars: 1,
            protein: 6,
            vitamin_a: 5,
            vitamin_c: 0,
            calcium: 2,
            iron: 4,
            restricciones: "Vegetariano",
            tipo: "Comida",
        },
        {
            name: "Galletitas de agua (30 g)",
            brand: "Aguila",
            href: "https://www.nutricionyentrenamiento.fit/images/alimento/397.jpg",
            calories: 135,
            total_fat: 5,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 0,
            sodium: 120,
            potassium: 20,
            total_carbs: 20,
            dietary_fiber: 1,
            sugars: 0,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 3,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Tostadas con mermelada (2 unidades)",
            brand: "Caseras",
            href: "https://www.justspices.es/media/recipe/Mix_Tostadas_Dulces_Tostada_dulce_con_mermelada_de_frambuesa-2.jpg",
            calories: 180,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 180,
            potassium: 70,
            total_carbs: 35,
            dietary_fiber: 2,
            sugars: 15,
            protein: 3,
            vitamin_a: 0,
            vitamin_c: 1,
            calcium: 2,
            iron: 3,
            restricciones: "Vegetariano",
            tipo: "Desayuno",
        },
        {
            name: "Ensalada mixta (300 g)",
            brand: "Natural Fresh",
            href: "https://www.clarin.com/img/2023/01/25/QQGYRANYD_1200x630__1.jpg",
            calories: 95,
            total_fat: 4,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 50,
            potassium: 450,
            total_carbs: 12,
            dietary_fiber: 5,
            sugars: 5,
            protein: 2,
            vitamin_a: 8,
            vitamin_c: 25,
            calcium: 4,
            iron: 3,
            restricciones: "Vegetariano, Vegano",
            tipo: "Almuerzo",
        },
        {
            name: "Barrita de cereal (1 unidad)",
            brand: "Cereal Mix",
            href: "https://arcorencasa.com/wp-content/uploads/2024/10/20241009-3786.webp",
            calories: 98,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 70,
            potassium: 55,
            total_carbs: 17,
            dietary_fiber: 1,
            sugars: 8,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Snack",
        },
        {
            name: "Té con leche (250 ml)",
            brand: "La Virginia",
            href: "https://i0.wp.com/elclubdelte.com/wp-content/uploads/2020/02/IMG_0253.jpeg?fit=712%2C475&ssl=1",
            calories: 75,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 5,
            sodium: 50,
            potassium: 150,
            total_carbs: 10,
            dietary_fiber: 0,
            sugars: 8,
            protein: 4,
            vitamin_a: 1,
            vitamin_c: 0,
            calcium: 12,
            iron: 0,
            restricciones: "Vegetariano",
            tipo: "Merienda",
        },
        {
            name: "Sopa de verduras (300 ml)",
            brand: "Knorr",
            href: "https://assets.unileversolutions.com/v1/87490005.png",
            calories: 110,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 450,
            potassium: 300,
            total_carbs: 18,
            dietary_fiber: 3,
            sugars: 4,
            protein: 4,
            vitamin_a: 15,
            vitamin_c: 20,
            calcium: 5,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Cena",
        },
        {
            name: "Guiso de lentejas (250 g)",
            brand: "Caserito",
            href: "https://resizer.glanacion.com/resizer/v2/guiso-de-lentejas-listo-en-15-HTNGFWAUH5GKJLMJVJH3NMMSDU.jpg?auth=1f45cc238ba9ce467d17eeae0635e2fc40ce0bb5e97c81cf1e2fffa619c6ee9e&width=880&height=586&quality=70&smart=true",
            calories: 310,
            total_fat: 7,
            saturated: 1,
            polyunsaturated: 2,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 0,
            sodium: 390,
            potassium: 600,
            total_carbs: 40,
            dietary_fiber: 10,
            sugars: 4,
            protein: 18,
            vitamin_a: 2,
            vitamin_c: 4,
            calcium: 6,
            iron: 9,
            restricciones: "Vegetariano",
            tipo: "Comida",
        },
        {
            name: "Pizza muzzarella (1 porción)",
            brand: "Pizzería Don Luis",
            href: "https://super-uno.com.ar/wp-content/uploads/2024/05/pizza-jpg.webp",
            calories: 290,
            total_fat: 12,
            saturated: 5,
            polyunsaturated: 1,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 18,
            sodium: 550,
            potassium: 180,
            total_carbs: 32,
            dietary_fiber: 2,
            sugars: 4,
            protein: 12,
            vitamin_a: 3,
            vitamin_c: 0,
            calcium: 15,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Cena",
        },
        {
            name: "Tarta de verduras (1 porción)",
            brand: "Veggie Express",
            href: "https://cdn0.uncomo.com/es/posts/5/8/8/como_hacer_tarta_de_verdura_36885_paso_10_600.jpg",
            calories: 240,
            total_fat: 9,
            saturated: 2,
            polyunsaturated: 2,
            monounsaturated: 4,
            trans: 0,
            cholesterol: 12,
            sodium: 330,
            potassium: 260,
            total_carbs: 28,
            dietary_fiber: 3,
            sugars: 3,
            protein: 8,
            vitamin_a: 7,
            vitamin_c: 5,
            calcium: 8,
            iron: 3,
            restricciones: "Vegetariano",
            tipo: "Almuerzo",
        },
        {
            name: "Smoothie de frutas (250 ml)",
            brand: "Green Shake",
            href: "https://e00-xlk-cooking-elmundo.uecdn.es/files/article_main_microformat_4_3/uploads/2023/02/28/63fe6ec911620.jpeg",
            calories: 160,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 25,
            potassium: 400,
            total_carbs: 35,
            dietary_fiber: 3,
            sugars: 28,
            protein: 2,
            vitamin_a: 10,
            vitamin_c: 30,
            calcium: 4,
            iron: 1,
            restricciones: "Vegetariano, Vegano",
            tipo: "Merienda",
        },
        {
            name: "Arroz con atún (250 g)",
            brand: "Casero",
            href: "https://imag.bonviveur.com/emplatado-final-del-arroz-con-atun-en-conserva.jpg",
            calories: 430,
            total_fat: 14,
            saturated: 3,
            polyunsaturated: 5,
            monounsaturated: 4,
            trans: 0,
            cholesterol: 35,
            sodium: 420,
            potassium: 300,
            total_carbs: 45,
            dietary_fiber: 2,
            sugars: 1,
            protein: 25,
            vitamin_a: 1,
            vitamin_c: 0,
            calcium: 3,
            iron: 4,
            restricciones: "",
            tipo: "Almuerzo",
        },
        {
            name: "Milanesa con puré (1 porción)",
            brand: "Cocina Criolla",
            href: "https://img-global.cpcdn.com/steps/36776663fe281927/400x400cq90/photo.jpg",
            calories: 520,
            total_fat: 25,
            saturated: 7,
            polyunsaturated: 3,
            monounsaturated: 10,
            trans: 1,
            cholesterol: 75,
            sodium: 640,
            potassium: 550,
            total_carbs: 35,
            dietary_fiber: 3,
            sugars: 2,
            protein: 30,
            vitamin_a: 0,
            vitamin_c: 6,
            calcium: 4,
            iron: 4,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Fideos con salsa boloñesa (1 plato)",
            brand: "Pasta d'Oro",
            href: "https://www.laespanolaaceites.com/wp-content/uploads/2019/05/espaguetis-a-la-bolonesa.jpg",
            calories: 610,
            total_fat: 20,
            saturated: 6,
            polyunsaturated: 2,
            monounsaturated: 7,
            trans: 0,
            cholesterol: 45,
            sodium: 420,
            potassium: 500,
            total_carbs: 65,
            dietary_fiber: 4,
            sugars: 8,
            protein: 24,
            vitamin_a: 4,
            vitamin_c: 3,
            calcium: 5,
            iron: 5,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Paella de mariscos (1 plato)",
            brand: "Sabores del Mar",
            href: "https://alicante.com.ar/wp-content/uploads/2022/06/26_receta-1200x900.jpg",
            calories: 490,
            total_fat: 15,
            saturated: 3,
            polyunsaturated: 4,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 65,
            sodium: 680,
            potassium: 470,
            total_carbs: 45,
            dietary_fiber: 2,
            sugars: 3,
            protein: 35,
            vitamin_a: 2,
            vitamin_c: 4,
            calcium: 6,
            iron: 8,
            restricciones: "Pescado, Mariscos",
            tipo: "Comida",
        },
        {
            name: "Wok de vegetales con tofu (1 porción)",
            brand: "Vegano Power",
            href: "https://www.hola.com/horizon/landscape/9b257b9352c8-wok-tofu-age-t.jpg",
            calories: 400,
            total_fat: 12,
            saturated: 2,
            polyunsaturated: 4,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 0,
            sodium: 320,
            potassium: 600,
            total_carbs: 35,
            dietary_fiber: 6,
            sugars: 6,
            protein: 18,
            vitamin_a: 10,
            vitamin_c: 20,
            calcium: 10,
            iron: 6,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Bife con ensalada (1 porción)",
            brand: "Granja Grill",
            href: "https://www.cucinare.tv/wp-content/uploads/2019/09/Bife-con-ensalada.jpg",
            calories: 480,
            total_fat: 22,
            saturated: 8,
            polyunsaturated: 2,
            monounsaturated: 9,
            trans: 1,
            cholesterol: 80,
            sodium: 150,
            potassium: 700,
            total_carbs: 10,
            dietary_fiber: 2,
            sugars: 3,
            protein: 40,
            vitamin_a: 1,
            vitamin_c: 6,
            calcium: 3,
            iron: 5,
            restricciones: "",
            tipo: "Comida",
        }
    ]);

    console.log('✅ Food inserted successfully.');
    await pool.end();
}

seedFoods().catch((err) => {
    console.error('❌ Error inserting seed data:', err);
    pool.end();
});
