import foodTable from '../src/food/food.entity';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';

const pool = new Pool({
    connectionString: process.env.DATABASE_URL ?? 'postgres://postgres:123456@localhost:5432/nutridigitaldb',
});

const db = drizzle(pool);

async function seedFoods() {

    await db.execute(
        `ALTER SEQUENCE food_id_seq RESTART WITH 1;`
    );

    await db.insert(foodTable).values([
        {
            name: "Manzana (200 g)",
            brand: "Frutas del Valle",
            href: "",
            calories: 122,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 0,
            potassium: 208,
            total_carbs: 30,
            dietary_fiber: 4,
            sugars: 24,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Fruta",
        },
        {
            name: "Banana (150 g)",
            brand: "Frutas del Valle",
            href: "",
            calories: 134,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 2,
            potassium: 537,
            total_carbs: 34,
            dietary_fiber: 4,
            sugars: 18,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Fruta",
        },
        {
            name: "Cafe (200 ml)",
            brand: "Nescafe",
            href: "",
            calories: 74,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 1,
            sodium: 76,
            potassium: 0,
            total_carbs: 13,
            dietary_fiber: 1,
            sugars: 10,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "Vegetariano, Vegano",
            tipo: "Bebida",
        },
        {
            name: "Medialuna (50 g)",
            brand: "Panaderia",
            href: "",
            calories: 158,
            total_fat: 7,
            saturated: 2,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 2,
            cholesterol: 0,
            sodium: 47,
            potassium: 0,
            total_carbs: 20,
            dietary_fiber: 1,
            sugars: 5,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Cerveza (1000 ml)",
            brand: "Patagonia",
            href: "",
            calories: 197,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 17,
            potassium: 85,
            total_carbs: 7,
            dietary_fiber: 0,
            sugars: 1,
            protein: 1,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Bebida",
        },
        {
            name: "Chocolate (40 g)",
            brand: "Bagley",
            href: "",
            calories: 200,
            total_fat: 11,
            saturated: 7,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 5,
            sodium: 5,
            potassium: 0,
            total_carbs: 25,
            dietary_fiber: 2,
            sugars: 20,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Coca Cola (355 ml)",
            brand: "Coca Cola",
            href: "",
            calories: 140,
            total_fat: 0,
            saturated: 0,
            polyunsaturated: 0,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 5,
            sodium: 45,
            potassium: 0,
            total_carbs: 39,
            dietary_fiber: 0,
            sugars: 39,
            protein: 0,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Bebida",
        },
        {
            name: "Hamburguesa (250 g)",
            brand: "Paty",
            href: "",
            calories: 516,
            total_fat: 25,
            saturated: 8,
            polyunsaturated: 5,
            monounsaturated: 9,
            trans: 1,
            cholesterol: 92,
            sodium: 712,
            potassium: 835,
            total_carbs: 38,
            dietary_fiber: 5,
            sugars: 10,
            protein: 35,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 0,
            iron: 0,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Yogur descremado (200 g)",
            brand: "La Serenísima",
            href: "",
            calories: 120,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 10,
            sodium: 85,
            potassium: 240,
            total_carbs: 16,
            dietary_fiber: 0,
            sugars: 14,
            protein: 10,
            vitamin_a: 2,
            vitamin_c: 1,
            calcium: 15,
            iron: 0,
            restricciones: "Vegetariano",
            tipo: "Lácteo",
        },
        {
            name: "Pollo a la plancha (150 g)",
            brand: "Granja Campo",
            href: "",
            calories: 275,
            total_fat: 8,
            saturated: 2,
            polyunsaturated: 2,
            monounsaturated: 3,
            trans: 0,
            cholesterol: 90,
            sodium: 70,
            potassium: 300,
            total_carbs: 0,
            dietary_fiber: 0,
            sugars: 0,
            protein: 40,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 6,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Pan integral (2 rebanadas)",
            brand: "Fargo",
            href: "",
            calories: 140,
            total_fat: 2,
            saturated: 0,
            polyunsaturated: 1,
            monounsaturated: 0,
            trans: 0,
            cholesterol: 0,
            sodium: 200,
            potassium: 80,
            total_carbs: 25,
            dietary_fiber: 4,
            sugars: 3,
            protein: 5,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 4,
            iron: 6,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Huevo duro (1 unidad)",
            brand: "Granja Los Pinos",
            href: "",
            calories: 78,
            total_fat: 5,
            saturated: 2,
            polyunsaturated: 1,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 186,
            sodium: 62,
            potassium: 63,
            total_carbs: 1,
            dietary_fiber: 0,
            sugars: 1,
            protein: 6,
            vitamin_a: 5,
            vitamin_c: 0,
            calcium: 2,
            iron: 4,
            restricciones: "Vegetariano",
            tipo: "Comida",
        },
        {
            name: "Galletitas de agua (30 g)",
            brand: "Aguila",
            href: "",
            calories: 135,
            total_fat: 5,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 0,
            sodium: 120,
            potassium: 20,
            total_carbs: 20,
            dietary_fiber: 1,
            sugars: 0,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 3,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Tostadas con mermelada (2 unidades)",
            brand: "Caseras",
            href: "",
            calories: 180,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 180,
            potassium: 70,
            total_carbs: 35,
            dietary_fiber: 2,
            sugars: 15,
            protein: 3,
            vitamin_a: 0,
            vitamin_c: 1,
            calcium: 2,
            iron: 3,
            restricciones: "Vegetariano",
            tipo: "Desayuno",
        },
        {
            name: "Ensalada mixta (300 g)",
            brand: "Natural Fresh",
            href: "",
            calories: 95,
            total_fat: 4,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 50,
            potassium: 450,
            total_carbs: 12,
            dietary_fiber: 5,
            sugars: 5,
            protein: 2,
            vitamin_a: 8,
            vitamin_c: 25,
            calcium: 4,
            iron: 3,
            restricciones: "Vegetariano, Vegano",
            tipo: "Almuerzo",
        },
        {
            name: "Barrita de cereal (1 unidad)",
            brand: "Cereal Mix",
            href: "",
            calories: 98,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 70,
            potassium: 55,
            total_carbs: 17,
            dietary_fiber: 1,
            sugars: 8,
            protein: 2,
            vitamin_a: 0,
            vitamin_c: 0,
            calcium: 1,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Snack",
        },
        {
            name: "Té con leche (250 ml)",
            brand: "La Virginia",
            href: "",
            calories: 75,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 5,
            sodium: 50,
            potassium: 150,
            total_carbs: 10,
            dietary_fiber: 0,
            sugars: 8,
            protein: 4,
            vitamin_a: 1,
            vitamin_c: 0,
            calcium: 12,
            iron: 0,
            restricciones: "Vegetariano",
            tipo: "Merienda",
        },
        {
            name: "Sopa de verduras (300 ml)",
            brand: "Knorr",
            href: "",
            calories: 110,
            total_fat: 3,
            saturated: 1,
            polyunsaturated: 1,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 450,
            potassium: 300,
            total_carbs: 18,
            dietary_fiber: 3,
            sugars: 4,
            protein: 4,
            vitamin_a: 15,
            vitamin_c: 20,
            calcium: 5,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Cena",
        },
        {
            name: "Guiso de lentejas (250 g)",
            brand: "Caserito",
            href: "",
            calories: 310,
            total_fat: 7,
            saturated: 1,
            polyunsaturated: 2,
            monounsaturated: 2,
            trans: 0,
            cholesterol: 0,
            sodium: 390,
            potassium: 600,
            total_carbs: 40,
            dietary_fiber: 10,
            sugars: 4,
            protein: 18,
            vitamin_a: 2,
            vitamin_c: 4,
            calcium: 6,
            iron: 9,
            restricciones: "Vegetariano",
            tipo: "Comida",
        },
        {
            name: "Pizza muzzarella (1 porción)",
            brand: "Pizzería Don Luis",
            href: "",
            calories: 290,
            total_fat: 12,
            saturated: 5,
            polyunsaturated: 1,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 18,
            sodium: 550,
            potassium: 180,
            total_carbs: 32,
            dietary_fiber: 2,
            sugars: 4,
            protein: 12,
            vitamin_a: 3,
            vitamin_c: 0,
            calcium: 15,
            iron: 2,
            restricciones: "Vegetariano",
            tipo: "Cena",
        },
        {
            name: "Tarta de verduras (1 porción)",
            brand: "Veggie Express",
            href: "",
            calories: 240,
            total_fat: 9,
            saturated: 2,
            polyunsaturated: 2,
            monounsaturated: 4,
            trans: 0,
            cholesterol: 12,
            sodium: 330,
            potassium: 260,
            total_carbs: 28,
            dietary_fiber: 3,
            sugars: 3,
            protein: 8,
            vitamin_a: 7,
            vitamin_c: 5,
            calcium: 8,
            iron: 3,
            restricciones: "Vegetariano",
            tipo: "Almuerzo",
        },
        {
            name: "Smoothie de frutas (250 ml)",
            brand: "Green Shake",
            href: "",
            calories: 160,
            total_fat: 2,
            saturated: 1,
            polyunsaturated: 0,
            monounsaturated: 1,
            trans: 0,
            cholesterol: 0,
            sodium: 25,
            potassium: 400,
            total_carbs: 35,
            dietary_fiber: 3,
            sugars: 28,
            protein: 2,
            vitamin_a: 10,
            vitamin_c: 30,
            calcium: 4,
            iron: 1,
            restricciones: "Vegetariano, Vegano",
            tipo: "Merienda",
        },
        {
            name: "Arroz con atún (250 g)",
            brand: "Casero",
            href: "",
            calories: 430,
            total_fat: 14,
            saturated: 3,
            polyunsaturated: 5,
            monounsaturated: 4,
            trans: 0,
            cholesterol: 35,
            sodium: 420,
            potassium: 300,
            total_carbs: 45,
            dietary_fiber: 2,
            sugars: 1,
            protein: 25,
            vitamin_a: 1,
            vitamin_c: 0,
            calcium: 3,
            iron: 4,
            restricciones: "",
            tipo: "Almuerzo",
        },
        {
            name: "Milanesa con puré (1 porción)",
            brand: "Cocina Criolla",
            href: "",
            calories: 520,
            total_fat: 25,
            saturated: 7,
            polyunsaturated: 3,
            monounsaturated: 10,
            trans: 1,
            cholesterol: 75,
            sodium: 640,
            potassium: 550,
            total_carbs: 35,
            dietary_fiber: 3,
            sugars: 2,
            protein: 30,
            vitamin_a: 0,
            vitamin_c: 6,
            calcium: 4,
            iron: 4,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Fideos con salsa boloñesa (1 plato)",
            brand: "Pasta d'Oro",
            href: "",
            calories: 610,
            total_fat: 20,
            saturated: 6,
            polyunsaturated: 2,
            monounsaturated: 7,
            trans: 0,
            cholesterol: 45,
            sodium: 420,
            potassium: 500,
            total_carbs: 65,
            dietary_fiber: 4,
            sugars: 8,
            protein: 24,
            vitamin_a: 4,
            vitamin_c: 3,
            calcium: 5,
            iron: 5,
            restricciones: "",
            tipo: "Comida",
        },
        {
            name: "Paella de mariscos (1 plato)",
            brand: "Sabores del Mar",
            href: "",
            calories: 490,
            total_fat: 15,
            saturated: 3,
            polyunsaturated: 4,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 65,
            sodium: 680,
            potassium: 470,
            total_carbs: 45,
            dietary_fiber: 2,
            sugars: 3,
            protein: 35,
            vitamin_a: 2,
            vitamin_c: 4,
            calcium: 6,
            iron: 8,
            restricciones: "Pescado, Mariscos",
            tipo: "Comida",
        },
        {
            name: "Wok de vegetales con tofu (1 porción)",
            brand: "Vegano Power",
            href: "",
            calories: 400,
            total_fat: 12,
            saturated: 2,
            polyunsaturated: 4,
            monounsaturated: 5,
            trans: 0,
            cholesterol: 0,
            sodium: 320,
            potassium: 600,
            total_carbs: 35,
            dietary_fiber: 6,
            sugars: 6,
            protein: 18,
            vitamin_a: 10,
            vitamin_c: 20,
            calcium: 10,
            iron: 6,
            restricciones: "Vegetariano, Vegano",
            tipo: "Comida",
        },
        {
            name: "Bife con ensalada (1 porción)",
            brand: "Granja Grill",
            href: "",
            calories: 480,
            total_fat: 22,
            saturated: 8,
            polyunsaturated: 2,
            monounsaturated: 9,
            trans: 1,
            cholesterol: 80,
            sodium: 150,
            potassium: 700,
            total_carbs: 10,
            dietary_fiber: 2,
            sugars: 3,
            protein: 40,
            vitamin_a: 1,
            vitamin_c: 6,
            calcium: 3,
            iron: 5,
            restricciones: "",
            tipo: "Comida",
        }
    ]);

    console.log('✅ Food inserted successfully.');
    await pool.end();
}

seedFoods().catch((err) => {
    console.error('❌ Error inserting seed data:', err);
    pool.end();
});
